
name: Platform Tests
on: [push, pull_request]
permissions:
  contents: read

jobs:
  platform_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.19.x', 'stable']

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: WillAbides/setup-go-faster@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Get dependencies
      run: sudo apt-get update && sudo apt-get install bsdiff

    - name: Test
      run: go test ./...
